// src/hooks/usePronunciationPractice.ts

import { useState, useCallback, useRef } from 'react';
import { useTTS } from './useTTS';
import { getLearningProfileService } from '@/lib/learning-profile-service';
import type { 
  PronunciationSession, 
  PronunciationWord, 
  PronunciationAttempt,
  PronunciationFeedback 
} from '@/types/pronunciation';

interface UsePronunciationPracticeReturn {
  isRecording: boolean;
  isPlaying: boolean;
  isAnalyzing: boolean;
  currentWord: PronunciationWord | null;
  session: PronunciationSession | null;
  error: string | null;
  
  startSession: (language: string, words: string[]) => Promise<void>;
  endSession: () => PronunciationSession;
  playWord: () => Promise<void>;
  playWordSlow: () => Promise<void>;
  startRecording: () => Promise<void>;
  stopRecording: () => Promise<PronunciationAttempt>;
  nextWord: () => void;
  previousWord: () => void;
}

export function usePronunciationPractice(): UsePronunciationPracticeReturn {
  const [isRecording, setIsRecording] = useState(false);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [currentWord, setCurrentWord] = useState<PronunciationWord | null>(null);
  const [session, setSession] = useState<PronunciationSession | null>(null);
  const [error, setError] = useState<string | null>(null);
  
  const { generateAudio, playAudio } = useTTS();
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const audioChunksRef = useRef<Blob[]>([]);
  const wordIndexRef = useRef(0);

  const startSession = useCallback(async (language: string, words: string[]) => {
    const pronunciationWords: PronunciationWord[] = words.map((word) => ({
      word,
      language,
      ipa: '', // Would be generated by backend
      audioUrl: '', // Would be generated by TTS
      attempts: [],
      mastered: false,
    }));

    const newSession: PronunciationSession = {
      id: crypto.randomUUID(),
      language,
      startedAt: new Date(),
      endedAt: null,
      words: pronunciationWords,
      overallScore: 0,
    };

    setSession(newSession);
    setCurrentWord(pronunciationWords[0]);
    wordIndexRef.current = 0;
    setError(null);
  }, []);

  const endSession = useCallback((): PronunciationSession => {
    if (!session) {
      throw new Error('No active session');
    }

    // Calculate overall score
    const allAttempts = session.words.flatMap(w => w.attempts);
    const avgScore = allAttempts.length > 0
      ? allAttempts.reduce((sum, a) => sum + a.score, 0) / allAttempts.length
      : 0;

    const endedSession: PronunciationSession = {
      ...session,
      endedAt: new Date(),
      overallScore: Math.round(avgScore),
    };

    // Update learning profile
    const updateProfile = async () => {
      try {
        const service = await getLearningProfileService();
        for (const word of session.words) {
          const issues = word.attempts.flatMap(a => a.feedback.issues);
          for (const issue of issues) {
            await service.recordPronunciationIssue(
              session.language,
              issue.expected,
              word.word
            );
          }
        }
      } catch (err) {
        console.error('Failed to update learning profile:', err);
      }
    };
    updateProfile();

    setSession(null);
    setCurrentWord(null);
    return endedSession;
  }, [session]);

  const playWord = useCallback(async () => {
    if (!currentWord) return;
    
    setIsPlaying(true);
    try {
      const audioData = await generateAudio(currentWord.word, currentWord.language);
      if (audioData) {
        await playAudio(audioData);
      }
    } finally {
      setIsPlaying(false);
    }
  }, [currentWord, generateAudio, playAudio]);

  const playWordSlow = useCallback(async () => {
    if (!currentWord) return;
    
    setIsPlaying(true);
    try {
      // For slow playback, we'd need TTS to support rate parameter
      // For now, just play normally
      const audioData = await generateAudio(currentWord.word, currentWord.language);
      if (audioData) {
        await playAudio(audioData);
      }
    } finally {
      setIsPlaying(false);
    }
  }, [currentWord, generateAudio, playAudio]);

  const startRecording = useCallback(async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const mediaRecorder = new MediaRecorder(stream);
      
      mediaRecorderRef.current = mediaRecorder;
      audioChunksRef.current = [];
      
      mediaRecorder.ondataavailable = (event) => {
        audioChunksRef.current.push(event.data);
      };
      
      mediaRecorder.start();
      setIsRecording(true);
    } catch (err) {
      setError('Failed to access microphone');
    }
  }, []);

  const stopRecording = useCallback(async (): Promise<PronunciationAttempt> => {
    if (!mediaRecorderRef.current || !currentWord) {
      throw new Error('Not recording');
    }

    return new Promise((resolve) => {
      mediaRecorderRef.current!.onstop = async () => {
        const audioBlob = new Blob(audioChunksRef.current, { type: 'audio/webm' });
        const audioUrl = URL.createObjectURL(audioBlob);
        
        setIsRecording(false);
        setIsAnalyzing(true);

        try {
          // Analyze pronunciation
          const feedback = await analyzePronunciation(
            currentWord.word,
            currentWord.language,
            audioBlob
          );

          const attempt: PronunciationAttempt = {
            id: crypto.randomUUID(),
            recordedAt: new Date(),
            audioUrl,
            score: feedback.overallScore,
            feedback,
          };

          // Update current word
          const updatedWord: PronunciationWord = {
            ...currentWord,
            attempts: [...currentWord.attempts, attempt],
            mastered: feedback.overallScore >= 80,
          };

          setCurrentWord(updatedWord);

          // Update session
          if (session) {
            const updatedWords = [...session.words];
            updatedWords[wordIndexRef.current] = updatedWord;
            setSession({ ...session, words: updatedWords });
          }

          resolve(attempt);
        } finally {
          setIsAnalyzing(false);
        }
      };

      mediaRecorderRef.current!.stop();
      mediaRecorderRef.current!.stream.getTracks().forEach(track => track.stop());
    });
  }, [currentWord, session]);

  const nextWord = useCallback(() => {
    if (!session) return;
    
    const nextIndex = wordIndexRef.current + 1;
    if (nextIndex < session.words.length) {
      wordIndexRef.current = nextIndex;
      setCurrentWord(session.words[nextIndex]);
    }
  }, [session]);

  const previousWord = useCallback(() => {
    if (!session) return;
    
    const prevIndex = wordIndexRef.current - 1;
    if (prevIndex >= 0) {
      wordIndexRef.current = prevIndex;
      setCurrentWord(session.words[prevIndex]);
    }
  }, [session]);

  return {
    isRecording,
    isPlaying,
    isAnalyzing,
    currentWord,
    session,
    error,
    startSession,
    endSession,
    playWord,
    playWordSlow,
    startRecording,
    stopRecording,
    nextWord,
    previousWord,
  };
}

// Pronunciation analysis (would call backend API)
async function analyzePronunciation(
  word: string,
  language: string,
  audioBlob: Blob
): Promise<PronunciationFeedback> {
  // In production, this would call a speech recognition API
  // For now, return mock feedback
  
  const score = 70 + Math.floor(Math.random() * 30);
  
  return {
    overallScore: score,
    accuracy: score - Math.floor(Math.random() * 10),
    fluency: score + Math.floor(Math.random() * 10),
    completeness: score,
    issues: score < 80 ? [
      {
        type: 'mispronunciation',
        position: Math.floor(word.length / 2),
        expected: 'expected sound',
        actual: 'actual sound',
        severity: 'minor',
      }
    ] : [],
    suggestions: score < 80 
      ? ['Try speaking more slowly', 'Focus on the middle syllable']
      : ['Great pronunciation!'],
  };
}