// src/app/page.tsx
"use client";

import { useState, useRef, useEffect } from 'react';
import Image from 'next/image';
import ReactMarkdown from 'react-markdown';

// -----------------------------------------------------------------------------
// Helper function to call backend APIs
// -----------------------------------------------------------------------------
async function callTranslateApi(text: string): Promise<string> {
  try {
    const response = await fetch('/api/translate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text })
    });

    if (!response.ok) {
      throw new Error('Translation API failed');
    }

    const reader = response.body?.getReader();
    if (!reader) {
      throw new Error('Failed to get response stream');
    }

    let result = '';
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      result += new TextDecoder().decode(value);
    }
    
    return result;
  } catch (err) {
    console.error('Translation API error:', err);
    throw new Error('Failed to translate text');
  }
}

async function callSummarizeApi(text: string): Promise<string> {
  try {
    const response = await fetch('/api/summarize', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text })
    });

    if (!response.ok) {
      throw new Error('Summarization API failed');
    }

    const reader = response.body?.getReader();
    if (!reader) {
      throw new Error('Failed to get response stream');
    }

    let result = '';
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      result += new TextDecoder().decode(value);
    }
    
    return result;
  } catch (err) {
    console.error('Summarization API error:', err);
    throw new Error('Failed to summarize text');
  }
}

// -----------------------------------------------------------------------------
// Main page component
// -----------------------------------------------------------------------------
export default function Home() {
  const [isRecording, setIsRecording] = useState(false);
  const [transcript, setTranscript] = useState('');
  const [translation, setTranslation] = useState('');
  const [summary, setSummary] = useState('');
  const [isTranslating, setIsTranslating] = useState(false);
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);
  
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const audioChunksRef = useRef<Blob[]>([]);

  // -------------------------------------------------------
  // Start recording with MediaRecorder API
  // -------------------------------------------------------
  const startRecording = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      mediaRecorderRef.current = new MediaRecorder(stream);
      audioChunksRef.current = [];

      mediaRecorderRef.current.ondataavailable = (event) => {
        audioChunksRef.current.push(event.data);
      };

      mediaRecorderRef.current.onstop = async () => {
        // Convert audio chunks to blob
        const audioBlob = new Blob(audioChunksRef.current, { type: 'audio/webm' });
        
        // Process audio with Whisper model
        setIsProcessing(true);
        try {
          // In a real implementation, you would upload the audio blob to your backend
          // which would then process it with Whisper
          // For now, we'll simulate the process
          
          // Simulate Whisper processing delay
          await new Promise(resolve => setTimeout(resolve, 2000));
          
          // Simulated transcript
          setTranscript("This is a simulated transcript from the recorded audio. In a real implementation, this would be generated by a Whisper model processing the actual audio input.");
        } catch (err) {
          console.error('Audio processing error:', err);
          alert('Failed to process audio');
        } finally {
          setIsProcessing(false);
        }
      };

      mediaRecorderRef.current.start();
      setIsRecording(true);
    } catch (err) {
      console.error('Error accessing microphone:', err);
      alert('Microphone access denied. Please enable microphone permissions.');
    }
  };

  // -------------------------------------------------------
  // Stop recording
  // -------------------------------------------------------
  const stopRecording = () => {
    if (mediaRecorderRef.current && isRecording) {
      mediaRecorderRef.current.stop();
      setIsRecording(false);
      
      // Stop all tracks
      if (mediaRecorderRef.current.stream) {
        mediaRecorderRef.current.stream.getTracks().forEach(track => track.stop());
      }
    }
  };

  // -------------------------------------------------------
  // Translate using backend API
  // -------------------------------------------------------
  const translate = async () => {
    if (!transcript) return;
    setIsTranslating(true);
    try {
      const result = await callTranslateApi(transcript);
      setTranslation(result);
    } catch (err) {
      console.error(err);
      alert('Translation failed');
    } finally {
      setIsTranslating(false);
    }
  };

  // -------------------------------------------------------
  // Summarize using backend API
  // -------------------------------------------------------
  const summarize = async () => {
    if (!translation) return;
    setIsSummarizing(true);
    try {
      const result = await callSummarizeApi(translation);
      setSummary(result);
    } catch (err) {
      console.error(err);
      alert('Summarization failed');
    } finally {
      setIsSummarizing(false);
    }
  };

  // -------------------------------------------------------
  // UI rendering
  // -------------------------------------------------------
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-zinc-50 font-sans dark:bg-black">
      {/* Header with logo */}
      <main className="flex flex-col items-center w-full max-w-3xl py-12 px-8 sm:px-12 bg-white dark:bg-black">
        <Image
          className="dark:invert"
          src="/next.svg"
          alt="Next.js logo"
          width={100}
          height={20}
          priority
        />

        {/* Recording controls */}
        <div className="mt-8 flex flex-col sm:flex-row gap-4">
          <button
            onClick={startRecording}
            disabled={isRecording || isProcessing}
            className="flex-1 flex items-center justify-center rounded-md px-4 py-2 bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50"
          >
            {isRecording ? 'Recording…' : isProcessing ? 'Processing…' : 'Start Recording'}
          </button>
          <button
            onClick={stopRecording}
            disabled={!isRecording}
            className="flex-1 flex items-center justify-center rounded-md px-4 py-2 bg-gray-600 text-white hover:bg-gray-700 disabled:opacity-50"
          >
            Stop Recording
          </button>
        </div>

        {/* Transcript display */}
        <div className="mt-6 w-full">
          <h2 className="font-semibold">Transcript</h2>
          <p className="border rounded p-2 bg-gray-100 dark:bg-gray-800 min-h-[60px]">{transcript || 'No transcript yet.'}</p>
        </div>

        {/* Translate button & result */}
        <div className="mt-4 w-full">
          <button
            onClick={translate}
            disabled={!transcript || isTranslating}
            className="flex items-center justify-center rounded-md px-4 py-2 bg-green-600 text-white hover:bg-green-700 disabled:opacity-50"
          >
            {isTranslating ? 'Translating…' : 'Translate to Spanish'}
          </button>
          <div className="border rounded p-2 mt-2 bg-gray-100 dark:bg-gray-800 min-h-[60px]">
            {translation || 'Translation will appear here.'}
          </div>
        </div>

        {/* Summarize button & result */}
        <div className="mt-4 w-full">
          <button
            onClick={summarize}
            disabled={!translation || isSummarizing}
            className="flex items-center justify-center rounded-md px-4 py-2 bg-purple-600 text-white hover:bg-purple-700 disabled:opacity-50"
          >
            {isSummarizing ? 'Summarizing…' : 'Summarize Spanish Text'}
          </button>
          <div className="border rounded p-2 mt-2 bg-gray-100 dark:bg-gray-800 min-h-[60px]">
            {summary ? <ReactMarkdown>{summary}</ReactMarkdown> : 'Summary will appear here.'}
          </div>
        </div>

        {/* Deployment & docs buttons (original links) */}
        <div className="flex flex-col gap-4 text-base font-medium sm:flex-row mt-8">
          <a
            className="flex h-12 w-full items-center justify-center gap-2 rounded-full bg-foreground px-5 text-background transition-colors hover:bg-[#383838] dark:hover:bg-[#ccc] md:w-[158px]"
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image className="dark:invert" src="/vercel.svg" alt="Vercel logomark" width={16} height={16} />
            Deploy Now
          </a>
          <a
            className="flex h-12 w-full items-center justify-center rounded-full border border-solid border-black/[.08] px-5 transition-colors hover:border-transparent hover:bg-black/[.04] dark:border-white/[.145] dark:hover:bg-[#1a1a1a] md:w-[158px]"
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Documentation
          </a>
        </div>
      </main>
    </div>
  );
}
